//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscaler) DeepCopyInto(out *AgenticAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscaler.
func (in *AgenticAutoscaler) DeepCopy() *AgenticAutoscaler {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgenticAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerList) DeepCopyInto(out *AgenticAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgenticAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerList.
func (in *AgenticAutoscalerList) DeepCopy() *AgenticAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgenticAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerSpec) DeepCopyInto(out *AgenticAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.RpsPerPodMin != nil {
		in, out := &in.RpsPerPodMin, &out.RpsPerPodMin
		*out = new(int32)
		**out = **in
	}
	if in.RpsPerPodMax != nil {
		in, out := &in.RpsPerPodMax, &out.RpsPerPodMax
		*out = new(int32)
		**out = **in
	}
	if in.MaxStepSize != nil {
		in, out := &in.MaxStepSize, &out.MaxStepSize
		*out = new(int32)
		**out = **in
	}
	if in.ScaleUpCooldownSeconds != nil {
		in, out := &in.ScaleUpCooldownSeconds, &out.ScaleUpCooldownSeconds
		*out = new(int32)
		**out = **in
	}
	if in.ScaleDownCooldownSeconds != nil {
		in, out := &in.ScaleDownCooldownSeconds, &out.ScaleDownCooldownSeconds
		*out = new(int32)
		**out = **in
	}
	if in.PreferredForecaster != nil {
		in, out := &in.PreferredForecaster, &out.PreferredForecaster
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerSpec.
func (in *AgenticAutoscalerSpec) DeepCopy() *AgenticAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerStatus) DeepCopyInto(out *AgenticAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.ClassifiedParams != nil {
		in, out := &in.ClassifiedParams, &out.ClassifiedParams
		*out = new(ClassifiedParams)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerStatus.
func (in *AgenticAutoscalerStatus) DeepCopy() *AgenticAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassifiedParams) DeepCopyInto(out *ClassifiedParams) {
	*out = *in
	in.ClassifiedAt.DeepCopyInto(&out.ClassifiedAt)
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(ContextFields)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassifiedParams.
func (in *ClassifiedParams) DeepCopy() *ClassifiedParams {
	if in == nil {
		return nil
	}
	out := new(ClassifiedParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextFields) DeepCopyInto(out *ContextFields) {
	*out = *in
	if in.HourlyProfile != nil {
		in, out := &in.HourlyProfile, &out.HourlyProfile
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextFields.
func (in *ContextFields) DeepCopy() *ContextFields {
	if in == nil {
		return nil
	}
	out := new(ContextFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossVersionObjectReference) DeepCopyInto(out *CrossVersionObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossVersionObjectReference.
func (in *CrossVersionObjectReference) DeepCopy() *CrossVersionObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossVersionObjectReference)
	in.DeepCopyInto(out)
	return out
}
